### ISSUE TITLE
新增的组件建议不带版本

### ISSUE THREAD

**Issue by chenyulun** [common-intellisense/tdesign-miniprogram1#1]
`react`有`@types/react`
`@pkgjs/parseargs`提示需要`@types/pkgjs__parseargs`
<img width="667" alt="image" src="https://github.com/user-attachments/assets/9d3dcdb7-e441-4218-928d-c4cba6c0f056">

版本用分支来进行管理，
`version-1`,
`version-2`

这样能减少很多包（个数）的发布（版本数量是减不了的），这样会不会好一点

**Comment by chenyulun** [comment]
现在制作的包导出的名称都要严格版本号？
统一导出固定的名称，比如`getPropsConfig`+`getUiComponents`

**Comment by Simon-He95** [comment]
我觉得是个好建议，仓库下面会看上去简洁很多
